### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by pombredanne** [jsocol/yodawg-py#1]
James: what would be the license for this fine code?

**Comment by jsocol** [comment]
You're not... you're not actually gonna try to use this for anything, are you? I would strongly recommend against using yodawg/yodawgd/yodawg-py for anything including educational purposes.

**Comment by pombredanne** [comment]
Just checking things out :P

**Comment by jsocol** [comment]
Added the license file, Apache2. But really, this whole stack is badly-written C by someone with no C and no datastructure background.
